### ISSUE TITLE
support Flat schema

### ISSUE THREAD

**Issue by TechQuery** [francescolorenzetti/types-4-strapi#6]
Cause of a wonderful plugin can flatten the response object of Strapi v4, we may add an option to control whether response is flatten:

https://market.strapi.io/plugins/strapi-plugin-transformer

@francescolorenzetti thanks your awesome tool, and have a good day~

**Comment by francescolorenzetti** [comment]
Considering this. 

But in the meantime, you can still use the existing generated types with that plugin, like this:

```ts
type TransformedUser = User['attributes']; 
```

**Comment by TechQuery** [comment]
> ```ts
> type TransformedUser = User['attributes']; 
> ```

But, this will lose `id` field...

**Comment by francescolorenzetti** [comment]
Marking this as `wontfix`. 

Since there is virtually an infinite number of potential transformations that could be applied to Strapi's responses, it seems to me that we simply cannot cover all cases. For the simple case of a 'flat' response (without the `attributes` key) you can use indexed access types with the utility type below:

```
type Transformed<A extends { attributes: any }> = A['attributes'] & {
  id: number;
};
```
